name=ME71_Car_Lib
version=0.0.2
author=Joel Velez <vilg302@mail.fresnostate.edu>
maintainer=Joel Velez <vilg302@mail.fresnostate.edu>
sentence=A library to manage the initialization of a small robot car and sensor set for the ME71 Class.
paragraph=This library initializes all the components neccessary to initialize the car for the ME71 Class.  It also provides helpful functions for control.  The purpose is to expose a simpel set of function to help student gain foundational skills in the application of hardware, without the overhead of libraries, and specialized sensor notation.
category=Other
url=https://github.com/thomas302/ME_71_Car
architectures=esp32
depends=Adafruit_VL53L0X,hd44780,Adafruit_NeoPixel
